name: Build and Publish a Docker Image CI

on:
  pull_request:
    types:
      - closed
    branches:
      - develop 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tinajassik/tcp-server-1:latest
    - name: Push image to Docker Hub
      run: docker push tinajassik/tcp-server-1:latest
